# Generated by Django 5.0.3 on 2024-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_shopmodel_sale_alter_commentmodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='sale',
            field=models.CharField(choices=[('ДА', 'ДА'), ('Нет', 'Нет')], max_length=100, verbose_name='Отобразить ли товар в список скидочных товаров  '),
        ),
    ]
